[package]
name = "goban"
version = "0.2.1"
authors = ["Samuel Batissou <samuelbatissou@gmail.com>"]
readme="README.md"
description= "Library for go move generation and go ruling."
edition = "2018"
license = "LGPL-3.0-only"
repository = "https://gitlab.com/SamBlaise/goban"
keywords=["go","goban","Igo","Baduk"]

[badges]
gitlab = {repository ="SamBlaise/goban"}
maintenance = {status = "actively-developed"}

[dependencies]
getset = "0.0.6"
[dev-dependencies]
rand = "0.6.4"
