[package]
name = "goban"
version = "0.1.0"
authors = ["Samuel Batissou <samuelbatissou@gmail.com>"]
description= "Library with go move genration and go ruling."
edition = "2018"
license = "LGPL-3.0-only"


[badges]
gitlab = {url="https://gitlab.com/SamBlaise/goban"}

[dependencies]
rand = "0.6.1"
