[package]
name = "goban"
version = "0.1.5"
authors = ["Samuel Batissou <samuelbatissou@gmail.com>"]
readme="README.md"
description= "Library for go move generation and go ruling."
edition = "2018"
license = "LGPL-3.0-only"


[badges]
gitlab = {repository ="SamBlaise/goban"}
maintenance = {status = "actively-developed"}

[dependencies]
rand = "0.6.1"
libc = "0.2.45"
