[package]
name = "goban"
version = "0.6.2"
authors = ["Samuel Batissou <samuelbatissou@gmail.com>"]
readme= "README.md"
description= "Library for go move generation and go ruling."
edition = "2018"
license = "MIT"
repository = "https://gitlab.com/Sabati/goban"
keywords=["go","goban","Igo","Baduk"]

[badges]
gitlab = {repository ="Sabati/goban"}
maintenance = {status = "actively-developed"}

[profile.release]
lto = true

[dependencies]
getset = "0.0.9"
lazy_static = "1.4.0"
rand_xorshift = "0.2.0"
rand = "0.7.2"
sgf-parser = "2.3.0"

[dev-dependencies]
criterion = "0.3.0"

[[bench]]
name = "perft"
harness = false
